### ISSUE TITLE
Error while attempting to download artifacts

### ISSUE THREAD

**Issue by sshindeBB** [blueflag/circle-get-artifact#2]
I m using "circle-get-artifact --token <CIRCLE_TOKEN> --user "sshinde" --project "BloomBoard-Research" --branch "feature/vishal/BBP-26" --path 'D:\' "
And It gives us error .Please let me know where i m gone wrong.
Error messege:
"C:\Windows\system32>circle-get-artifact --token <CIRCLE_TOKEN> --user "sshindeBB" --project "BloomBoard-Research" --branch "feature/vishal/BBP-26"
Error while attempting to download artifacts:
Error: HTTP client error 404
    at CircleCIResponse.clientError (C:\Users\Admin\AppData\Roaming\npm\node_modules\circle-get-artifact\node_modules\circleci\dist\circleci-response.js:16:16)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\circle-get-artifact\node_modules\circleci\dist\circleci-request.js:109:43
    at Request._callback (C:\Users\Admin\AppData\Roaming\npm\node_modules\circle-get-artifact\node_modules\circleci\dist\circleci-request.js:95:48)
    at Request.self.callback (C:\Users\Admin\AppData\Roaming\npm\node_modules\circle-get-artifact\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\circle-get-artifact\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\circle-get-artifact\node_modules\request\request.js:1085:12)
"

**Comment by thepont** [comment]
Hey @sshindeBB, 

The issue is that the `--path` parameter refers to the remote path of the artifact, not the local path for where you want to put the artifact.

If you don't use the path parameter it should attempt to download all artifacts from the build.

In circle on your build the Artifacts tab should allow you to see the path of your files.

On another note, sometimes artifacts go randomly missing from CircleCI builds and the build needs to be rebuilt, It might be worth trying to rebuild then try the download again
